.PHONY: build test program load clean

build:
	vivado -nolog -nojournal -mode batch -source ../../script/build.tcl

test:
	iverilog -g2012 -o testbench.vvp testbench.v z1top.v
	vvp testbench.vvp

program:
	vivado -nolog -nojournal -mode batch -source ../../script/program.tcl

load: program

clean:
	$(RM) -r .Xil
	$(RM) webtalk* usage_statistics_webtalk*
	$(RM) *.vcd *.vvp *.bit *.dcp
